server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: discovery-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 5