server:
  port: 8090
spring:
  profiles:
    include: discovery

---
# Discovery
spring:
  profiles: discovery

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_DOMAIN:localhost}:8761/eureka/
  instance:
    preferIpAddress: true
