server.port: 8091

spring:
  profiles:
    active: discovery

---

# Discovery Client
spring:
  profiles: discovery
  cloud:
    config:
      enabled: true
      failFast: true
      discovery:
        enabled: true
        serviceId: config-server
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/